<a href="https://colab.research.google.com/github/akilchen/pandas_exercise/blob/main/CH02_DataFrame%E7%9A%84%E9%81%8B%E7%AE%97%E6%8A%80%E5%B7%A7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np

Mounted at /content/drive

# **2.1 Select出DataFrame的欄位:用index**

01 讀取movies.csv,將多個col_name以list形式傳給[ ]，做出一個subquery

In [ ]:
movies = pd.read_csv('/content/drive/MyDrive/Pandas/data/movie.csv')
movies_actor_director = movies[['actor_1_name','actor_2_name','actor_3_name','director_name']]
movies_actor_director.head()

      actor_1_name      actor_2_name          actor_3_name      director_name
0      CCH Pounder  Joel David Moore             Wes Studi      James Cameron
1      Johnny Depp     Orlando Bloom        Jack Davenport     Gore Verbinski
2  Christoph Waltz      Rory Kinnear      Stephanie Sigman         Sam Mendes
3        Tom Hardy    Christian Bale  Joseph Gordon-Levitt  Christopher Nolan
4      Doug Walker        Rob Walker                   NaN        Doug Walker

In [ ]:
#如果你嫌欄位很多的話，你可以這樣做:
cols = ['actor_1_name','actor_2_name','actor_3_name','director_name']
movies_actor_director = movies[cols]
movies_actor_director.head()

      actor_1_name      actor_2_name          actor_3_name      director_name
0      CCH Pounder  Joel David Moore             Wes Studi      James Cameron
1      Johnny Depp     Orlando Bloom        Jack Davenport     Gore Verbinski
2  Christoph Waltz      Rory Kinnear      Stephanie Sigman         Sam Mendes
3        Tom Hardy    Christian Bale  Joseph Gordon-Levitt  Christopher Nolan
4      Doug Walker        Rob Walker                   NaN        Doug Walker

**(重要)02 想要select一個column,用object(成為Series)和list(成為DataFrame)方式的差別

In [ ]:
#用Series選取欄位
type(movies['director_name'])

pandas.core.series.Series

In [ ]:
#用DataFrame選取欄位
type(movies[['director_name']])

pandas.core.frame.DataFrame

03 以loc[]attribute來select column<br>
(1)先用slice ":" select 所有rows<br>
(2)指定col_name

In [ ]:
type(movies.loc[:,'director_name'])

pandas.core.series.Series

In [ ]:
type(movies.loc[:,['director_name']])

pandas.core.frame.DataFrame

# **2.2 Select出DataFrame的欄位:用method**

基本上就兩個方式:select_dtypes()及filter()

01 讀取movies.csv,output不同dytpes的col數量

In [ ]:
movies = pd.read_csv('/content/drive/MyDrive/Pandas/data/movie.csv')
movies.dtypes.value_counts()

float64    13
object     12
int64       3
Name: count, dtype: int64

02 用select_types找出具有object的column<br>
(include參數可接受單一object或list，如果是不包含可以用exclude)

In [ ]:
movies.select_dtypes(include=['object']).head()

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,actor_3_name,plot_keywords,movie_imdb_link,language,country,content_rating
0,Color,James Cameron,Joel David Moore,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,Wes Studi,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,English,USA,PG-13
1,Color,Gore Verbinski,Orlando Bloom,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,Jack Davenport,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,English,USA,PG-13
2,Color,Sam Mendes,Rory Kinnear,Action|Adventure|Thriller,Christoph Waltz,Spectre,Stephanie Sigman,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,English,UK,PG-13
3,Color,Christopher Nolan,Christian Bale,Action|Thriller,Tom Hardy,The Dark Knight Rises,Joseph Gordon-Levitt,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,English,USA,PG-13
4,NaN,Doug Walker,Rob Walker,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN

03 用select_types找出具有數值欄位(用number)的column

In [ ]:
movies.select_dtypes(include=['number']).head()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,723.0,178.0,0.0,855.0,1000.0,760505847.0,886204,4834,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000
1,302.0,169.0,563.0,1000.0,40000.0,309404152.0,471220,48350,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0
2,602.0,148.0,0.0,161.0,11000.0,200074175.0,275868,11700,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000
3,813.0,164.0,22000.0,23000.0,27000.0,448130642.0,1144337,106759,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,NaN,131.0,NaN,131.0,NaN,8,143,0.0,NaN,NaN,NaN,12.0,7.1,NaN,0

04 用select_types找出具有int和object欄位的column

In [ ]:
movies.select_dtypes(include=['int','object']).head()

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,plot_keywords,movie_imdb_link,language,country,content_rating,movie_facebook_likes
0,Color,James Cameron,Joel David Moore,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,English,USA,PG-13,33000
1,Color,Gore Verbinski,Orlando Bloom,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,English,USA,PG-13,0
2,Color,Sam Mendes,Rory Kinnear,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,English,UK,PG-13,85000
3,Color,Christopher Nolan,Christian Bale,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,English,USA,PG-13,164000
4,NaN,Doug Walker,Rob Walker,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,0

05 用select_types排除具有float欄位的column

In [ ]:
movies.select_dtypes(exclude=['float']).head()

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,plot_keywords,movie_imdb_link,language,country,content_rating,movie_facebook_likes
0,Color,James Cameron,Joel David Moore,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,English,USA,PG-13,33000
1,Color,Gore Verbinski,Orlando Bloom,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,English,USA,PG-13,0
2,Color,Sam Mendes,Rory Kinnear,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,English,UK,PG-13,85000
3,Color,Christopher Nolan,Christian Bale,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,English,USA,PG-13,164000
4,NaN,Doug Walker,Rob Walker,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,0

06 用fliter()撈出包含"fb"欄位的column

In [ ]:
movies.filter(like='facebook').head()

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0

08 用fliter()撈出column裡有包含數字的(用regex regular expression)

In [ ]:
movies.filter(regex='\d').head()

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0

# **2.3 排序col_name**

01 讀取movies.csv,整理部分col_name,讓它更簡單

In [ ]:
movies = pd.read_csv('/content/drive/MyDrive/Pandas/data/movie.csv')
def shorten(col_name):
  return (col_name.replace('facebook_likes','fb').replace('for_reviews',''))

movies = movies.rename(columns=shorten)
movies.columns

Index(['color', 'director_name', 'num_critic_', 'duration', 'director_fb',
       'actor_3_fb', 'actor_2_name', 'actor_1_fb', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users', 'cast_total_fb',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_fb', 'imdb_score', 'aspect_ratio',
       'movie_fb'],
      dtype='object')

03 更據欄位類型進行分類，進而產生多個col_name的分組list

In [ ]:
cate_core = ['movie_title', 'title_year','content_rating','genres']
cate_people = ['director_name','actor_1_name','actor_2_name','actor_3_name']
cate_other = ['color','country', 'language', 'plot_keywords', 'movie_imdb_link']

cont_fb = ['director_fb','actor_1_fb','actor_2_fb','actor_3_fb','cast_total_fb','movie_fb']
cont_finance =['budget','gross']
cont_num_reviews =['num_voted_users','num_user_','num_critic_']
cont_other =[ 'imdb_score','duration', 'aspect_ratio','facenumber_in_poster']

04 更據自己希望的方式將各組別串接起來，使用set()

In [ ]:
new_col_order = cate_core+cate_people+cate_other+cont_fb+cont_finance+cont_num_reviews+cont_other
set(movies.columns) == set(new_col_order)

True

05 將從新排好的col_name列出新的DataFrame

In [ ]:
movies[new_col_order].head()

,movie_title,title_year,content_rating,genres,director_name,actor_1_name,actor_2_name,actor_3_name,color,country,...,movie_fb,budget,gross,num_voted_users,num_user_,num_critic_,imdb_score,duration,aspect_ratio,facenumber_in_poster
0,Avatar,2009.0,PG-13,Action|Adventure|Fantasy|Sci-Fi,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Color,USA,...,33000,237000000.0,760505847.0,886204,3054.0,723.0,7.9,178.0,1.78,0.0
1,Pirates of the Caribbean: At World's End,2007.0,PG-13,Action|Adventure|Fantasy,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Color,USA,...,0,300000000.0,309404152.0,471220,1238.0,302.0,7.1,169.0,2.35,0.0
2,Spectre,2015.0,PG-13,Action|Adventure|Thriller,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Color,UK,...,85000,245000000.0,200074175.0,275868,994.0,602.0,6.8,148.0,2.35,1.0
3,The Dark Knight Rises,2012.0,PG-13,Action|Thriller,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Color,USA,...,164000,250000000.0,448130642.0,1144337,2701.0,813.0,8.5,164.0,2.35,0.0
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,Documentary,Doug Walker,Doug Walker,Rob Walker,NaN,NaN,NaN,...,0,NaN,NaN,8,NaN,NaN,7.1,NaN,NaN,0.0

# **2.4 DataFrame的統計方法**

01 讀取movie.csv,用shape、size、ndim取得其基本屬性，之後執行len()取得列數

In [ ]:
movies = pd.read_csv('/content/drive/MyDrive/Pandas/data/movie.csv')
print("shape=",movies.shape) #列數、行數(傳回tuple)
print('size=',movies.size)  #資料總數(4916*28)
print('ndim=',movies.ndim)  #維度數(軸數axis)
print('rows=',len(movies))  #列數
print('columns=',len(movies.columns))  #行數

shape= (4916, 28)
size= 137648
ndim= 2
rows= 4916
columns= 28

02 用count()顯示每一個欄位的no missing values,並output每一個欄位為index的Series:

In [ ]:
movies.count()

color                        4897
director_name                4814
num_critic_for_reviews       4867
duration                     4901
director_facebook_likes      4814
actor_3_facebook_likes       4893
actor_2_name                 4903
actor_1_facebook_likes       4909
gross                        4054
genres                       4916
actor_1_name                 4909
movie_title                  4916
num_voted_users              4916
cast_total_facebook_likes    4916
actor_3_name                 4893
facenumber_in_poster         4903
plot_keywords                4764
movie_imdb_link              4916
num_user_for_reviews         4895
language                     4902
country                      4911
content_rating               4616
budget                       4432
title_year                   4810
actor_2_facebook_likes       4903
imdb_score                   4916
aspect_ratio                 4590
movie_facebook_likes         4916
dtype: int64

03 min(),max(),mean(),median()和std()等統計方法會傳回一個Series。

In [ ]:
movies.select_dtypes(include=np.number).min()

num_critic_for_reviews          1.00
duration                        7.00
director_facebook_likes         0.00
actor_3_facebook_likes          0.00
actor_1_facebook_likes          0.00
gross                         162.00
num_voted_users                 5.00
cast_total_facebook_likes       0.00
facenumber_in_poster            0.00
num_user_for_reviews            1.00
budget                        218.00
title_year                   1916.00
actor_2_facebook_likes          0.00
imdb_score                      1.60
aspect_ratio                    1.18
movie_facebook_likes            0.00
dtype: float64

In [ ]:
max = movies.select_dtypes(include=np.number).max()
formatted_max = max.apply(lambda x: f"{x:.2f}")  #使用字串格式化來控制輸出的格式，:.2f 表示將數值格式化為小數點後兩位的浮點數。
formatted_max

num_critic_for_reviews              813.00
duration                            511.00
director_facebook_likes           23000.00
actor_3_facebook_likes            23000.00
actor_1_facebook_likes           640000.00
gross                         760505847.00
num_voted_users                 1689764.00
cast_total_facebook_likes        656730.00
facenumber_in_poster                 43.00
num_user_for_reviews               5060.00
budget                       4200000000.00
title_year                         2016.00
actor_2_facebook_likes           137000.00
imdb_score                            9.50
aspect_ratio                         16.00
movie_facebook_likes             349000.00
dtype: object

In [ ]:
mean = movies.select_dtypes(include=np.number).mean()
formatted_mean = mean.apply(lambda x: f"{x:.2f}")  #使用字串格式化來控制輸出的格式，:.2f 表示將數值格式化為小數點後兩位的浮點數。
formatted_mean

num_critic_for_reviews            137.99
duration                          107.09
director_facebook_likes           691.01
actor_3_facebook_likes            631.28
actor_1_facebook_likes           6494.49
gross                        47644514.53
num_voted_users                 82644.92
cast_total_facebook_likes        9579.82
facenumber_in_poster                1.38
num_user_for_reviews              267.67
budget                       36547486.03
title_year                       2002.45
actor_2_facebook_likes           1621.92
imdb_score                          6.44
aspect_ratio                        2.22
movie_facebook_likes             7348.29
dtype: object

In [ ]:
median = movies.select_dtypes(include=np.number).median()
formatted_median = median.apply(lambda x: f"{x:.2f}")  #使用字串格式化來控制輸出的格式，:.2f 表示將數值格式化為小數點後兩位的浮點數。
formatted_median

num_critic_for_reviews            108.00
duration                          103.00
director_facebook_likes            48.00
actor_3_facebook_likes            366.00
actor_1_facebook_likes            982.00
gross                        25043962.00
num_voted_users                 33132.50
cast_total_facebook_likes        3049.00
facenumber_in_poster                1.00
num_user_for_reviews              153.00
budget                       19850000.00
title_year                       2005.00
actor_2_facebook_likes            593.00
imdb_score                          6.60
aspect_ratio                        2.35
movie_facebook_likes              159.00
dtype: object

In [ ]:
std = movies.select_dtypes(include=np.number).std()
formatted_std = std.apply(lambda x: f"{x:.2f}")  #使用字串格式化來控制輸出的格式，:.2f 表示將數值格式化為小數點後兩位的浮點數。
#lambda x: f"{x:.2f}" 是一個匿名函式，它會將每個元素 x 格式化為小數點後兩位的浮點數字串。
formatted_std

num_critic_for_reviews             120.24
duration                            25.29
director_facebook_likes           2832.95
actor_3_facebook_likes            1625.87
actor_1_facebook_likes           15106.99
gross                         67372553.83
num_voted_users                 138322.16
cast_total_facebook_likes        18164.32
facenumber_in_poster                 2.02
num_user_for_reviews               372.93
budget                       100242679.25
title_year                          12.45
actor_2_facebook_likes            4011.30
imdb_score                           1.13
aspect_ratio                         1.40
movie_facebook_likes             19206.02
dtype: object

04 用describe()進行描述性統計資料及四分位數。T為轉置攔位。<br>
<br>
Gemini葛格說:
apply() 適用於對整行或整列進行操作，例如計算總和、平均值等。<br>
applymap() 適用於對 DataFrame 中的每一個元素進行操作，例如格式化、轉換等。<br>
在這個情況下，我們需要對 DataFrame 中的每一個數值進行格式化，因此 applymap() 是更適合的選擇。

In [ ]:
described_movies = movies.describe().T

# 使用applymap()和字串格式化，將每個元素都格式化為小數點後兩位
formatted_described_movies = described_movies.applymap(lambda x: f"{x:.2f}")
formatted_described_movies

<ipython-input-44-7f3666dca983>:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  formatted_described_movies = described_movies.applymap(lambda x: f"{x:.2f}")

,count,mean,std,min,25%,50%,75%,max
num_critic_for_reviews,4867.00,137.99,120.24,1.00,49.00,108.00,191.00,813.00
duration,4901.00,107.09,25.29,7.00,93.00,103.00,118.00,511.00
director_facebook_likes,4814.00,691.01,2832.95,0.00,7.00,48.00,189.75,23000.00
actor_3_facebook_likes,4893.00,631.28,1625.87,0.00,132.00,366.00,633.00,23000.00
actor_1_facebook_likes,4909.00,6494.49,15106.99,0.00,607.00,982.00,11000.00,640000.00
gross,4054.00,47644514.53,67372553.83,162.00,5019656.25,25043962.00,61108412.75,760505847.00
num_voted_users,4916.00,82644.92,138322.16,5.00,8361.75,33132.50,93772.75,1689764.00
cast_total_facebook_likes,4916.00,9579.82,18164.32,0.00,1394.75,3049.00,13616.75,656730.00
facenumber_in_poster,4903.00,1.38,2.02,0.00,0.00,1.00,2.00,43.00
num_user_for_reviews,4895.00,267.67,372.93,1.00,64.00,153.00,320.50,5060.00
budget,4432.00,36547486.03,100242679.25,218.00,6000000.00,19850000.00,43000000.00,4200000000.00
title_year,4810.00,2002.45,12.45,1916.00,1999.00,2005.00,2011.00,2016.00
actor_2_facebook_likes,4903.00,1621.92,4011.30,0.00,277.00,593.00,912.00,137000.00
imdb_score,4916.00,6.44,1.13,1.60,5.80,6.60,7.20,9.50
aspect_ratio,4590.00,2.22,1.40,1.18,1.85,2.35,2.35,16.00
movie_facebook_likes,4916.00,7348.29,19206.02,0.00,0.00,159.00,2000.00,349000.00

05 describe()預設顯示四分位數，而我們也能用pencentiles來指定其他分位數。

In [ ]:
described_movies = movies.describe(percentiles=[.99]).T

# 使用applymap()和字串格式化，將每個元素都格式化為小數點後兩位
formatted_described_movies = described_movies.applymap(lambda x: f"{x:.2f}")
formatted_described_movies

<ipython-input-45-25c1dd5274bc>:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  formatted_described_movies = described_movies.applymap(lambda x: f"{x:.2f}")

,count,mean,std,min,50%,99%,max
num_critic_for_reviews,4867.00,137.99,120.24,1.00,108.00,546.68,813.00
duration,4901.00,107.09,25.29,7.00,103.00,189.00,511.00
director_facebook_likes,4814.00,691.01,2832.95,0.00,48.00,16000.00,23000.00
actor_3_facebook_likes,4893.00,631.28,1625.87,0.00,366.00,11000.00,23000.00
actor_1_facebook_likes,4909.00,6494.49,15106.99,0.00,982.00,44920.00,640000.00
gross,4054.00,47644514.53,67372553.83,162.00,25043962.00,326412798.32,760505847.00
num_voted_users,4916.00,82644.92,138322.16,5.00,33132.50,681584.60,1689764.00
cast_total_facebook_likes,4916.00,9579.82,18164.32,0.00,3049.00,62413.90,656730.00
facenumber_in_poster,4903.00,1.38,2.02,0.00,1.00,8.00,43.00
num_user_for_reviews,4895.00,267.67,372.93,1.00,153.00,1999.24,5060.00
budget,4432.00,36547486.03,100242679.25,218.00,19850000.00,200000000.00,4200000000.00
title_year,4810.00,2002.45,12.45,1916.00,2005.00,2016.00,2016.00
actor_2_facebook_likes,4903.00,1621.92,4011.30,0.00,593.00,17000.00,137000.00
imdb_score,4916.00,6.44,1.13,1.60,6.60,8.50,9.50
aspect_ratio,4590.00,2.22,1.40,1.18,2.35,4.00,16.00
movie_facebook_likes,4916.00,7348.29,19206.02,0.00,159.00,93850.00,349000.00

# **2.5 DataFrame Chaining**